_wandb:
    value:
        cli_version: 0.18.3
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 55
            "2":
                - 1
                - 11
                - 49
                - 51
                - 55
            "3":
                - 2
                - 13
                - 23
                - 55
            "4": 3.9.6
            "5": 0.18.3
            "6": 4.45.2
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
